---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: piper
  namespace: default
  labels:
    app: piper
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: piper
  template:
    metadata:
      labels:
        app: piper
    spec:
      containers:
        - name: piper
          image: rhasspy/wyoming-piper:latest
          args: ["--voice", "en_US-hfc_female-medium"]
          imagePullPolicy: Always
          ports:
            - containerPort: 10200
      nodeName: node100

---
apiVersion: v1
kind: Service
metadata:
  name: piper
  namespace: default
spec:
  selector:
    app: piper
  ports:
    - name: piper
      protocol: TCP
      port: 10200
      nodePort: 30204
  type: NodePort

